import base64
import logging
import os

import httpx

from app.config import settings

logger = logging.getLogger(__name__)

GRAPH_SEND_MAIL_URL = "https://graph.microsoft.com/v1.0/users/{sender}/sendMail"

NO_FINDINGS_BODY_TEMPLATE = """Dear {company} Team,

We have completed your Microsoft 365 Security Assessment, however the scan was unable to collect sufficient data to generate a report.

This is typically caused by one of the following:
- The consent or permissions granted during the assessment request were incomplete
- The Microsoft 365 tenant has not yet propagated the required API permissions
- A connectivity issue occurred during the scan

What to do next:
Please reply to this email or contact our team and we will arrange a re-scan at no charge.

We apologise for the inconvenience.

Best regards,
{from_name}
"""

EMAIL_BODY_TEMPLATE = """Dear {company} Team,

Your complimentary Microsoft 365 Security Assessment is now complete.

Please find your confidential security report attached to this email.

IMPORTANT: This report contains sensitive security findings about your Microsoft 365 environment.
Please share it only with your IT leadership and security team.

Report highlights included:
- Full Microsoft Entra ID (Azure AD) audit
- Exchange Online security review
- SharePoint Online configuration assessment
- Microsoft Teams security posture
- Microsoft Purview compliance review
- M365 Admin Portal configuration review
- AI-generated remediation roadmap

If you have questions about any findings or need help with remediation,
please don't hesitate to reach out to our team.

Best regards,
{from_name}

---
This report was generated by an AI Automated Microsoft 365 Security Assessment.
All findings reflect the configuration at the time of the assessment.
"""


def _get_graph_token() -> str:
    """Acquire an app-only token for our own tenant (for sending email via Graph)."""
    from app.services.graph_admin import _get_token_for_tenant
    return _get_token_for_tenant(settings.AZURE_TENANT_ID)


def send_no_findings_email(to_email: str, company: str) -> None:
    """Send a notification email when the scan produced no collectible findings."""
    logger.info("Sending no-findings notification to %s for %s", to_email, company)
    token = _get_graph_token()

    body_text = NO_FINDINGS_BODY_TEMPLATE.format(
        company=company,
        from_name=settings.EMAIL_FROM_NAME,
    )

    message: dict = {
        "message": {
            "subject": f"Your M365 Security Assessment — Action Required ({company})",
            "body": {"contentType": "Text", "content": body_text},
            "toRecipients": [{"emailAddress": {"address": to_email}}],
        },
        "saveToSentItems": "true",
    }

    url = GRAPH_SEND_MAIL_URL.format(sender=settings.EMAIL_FROM)
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    response = httpx.post(url, json=message, headers=headers, timeout=30)

    if response.status_code == 202:
        logger.info("No-findings notification sent to %s", to_email)
    else:
        raise RuntimeError(
            f"Graph API sendMail failed: {response.status_code} {response.text}"
        )


def send_admin_alert(subject: str, body: str) -> None:
    """Send an operational alert to the configured ADMIN_EMAIL address."""
    logger.info("Sending admin alert: %s", subject)
    try:
        token = _get_graph_token()
        message: dict = {
            "message": {
                "subject": subject,
                "body": {"contentType": "Text", "content": body},
                "toRecipients": [{"emailAddress": {"address": settings.ADMIN_EMAIL}}],
            },
            "saveToSentItems": "true",
        }
        url = GRAPH_SEND_MAIL_URL.format(sender=settings.EMAIL_FROM)
        headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
        response = httpx.post(url, json=message, headers=headers, timeout=30)
        if response.status_code != 202:
            logger.error("Admin alert failed: %s %s", response.status_code, response.text[:200])
    except Exception as exc:
        # Admin alerts must never crash the caller
        logger.error("Admin alert could not be sent: %s", exc)


def send_report_email(to_email: str, company: str, pdf_path: str) -> None:
    """Send the PDF report via Microsoft Graph API (no SMTP, app-only OAuth2).

    Always BCC's ADMIN_EMAIL so every client report is archived on the admin side.
    The BCC is invisible to the client recipient.
    """
    logger.info("Acquiring Graph token to send report to %s", to_email)
    token = _get_graph_token()

    body_text = EMAIL_BODY_TEMPLATE.format(
        company=company,
        from_name=settings.EMAIL_FROM_NAME,
    )

    message: dict = {
        "message": {
            "subject": f"Your M365 Security Assessment Report — {company}",
            "body": {"contentType": "Text", "content": body_text},
            "toRecipients": [{"emailAddress": {"address": to_email}}],
        },
        "saveToSentItems": "true",
    }

    # BCC admin on every report — invisible to client, easy to change via ADMIN_EMAIL env var
    if settings.ADMIN_EMAIL and settings.ADMIN_EMAIL.lower() != to_email.lower():
        message["message"]["bccRecipients"] = [
            {"emailAddress": {"address": settings.ADMIN_EMAIL}}
        ]

    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, "rb") as f:
            pdf_b64 = base64.b64encode(f.read()).decode()
        filename = f"M365_Security_Assessment_{company.replace(' ', '_')}.pdf"
        message["message"]["attachments"] = [
            {
                "@odata.type": "#microsoft.graph.fileAttachment",
                "name": filename,
                "contentType": "application/pdf",
                "contentBytes": pdf_b64,
            }
        ]

    url = GRAPH_SEND_MAIL_URL.format(sender=settings.EMAIL_FROM)
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    logger.info("Sending report email via Graph API to %s for %s", to_email, company)
    response = httpx.post(url, json=message, headers=headers, timeout=30)

    if response.status_code == 202:
        logger.info("Report email sent to %s", to_email)
    else:
        raise RuntimeError(
            f"Graph API sendMail failed: {response.status_code} {response.text}"
        )

    # Clean up PDF after sending
    if pdf_path and os.path.exists(pdf_path):
        os.unlink(pdf_path)
        logger.info("Cleaned up PDF: %s", pdf_path)
